In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.2 kB ? eta -:--:--
     ---------------------------------------- 61.2/61.2 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 660.6 kB/s eta 0:00:24
   ---------------------------------------- 0.1/15.8 MB 1.3 MB/s eta 0:00:12
    --------------------------------------- 0.3/15.8 MB 1.9 MB/s eta 0:00:09
   - -------------------------------------- 0.6/15.8 MB 2.9 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/15.8 MB 3.5 MB/s eta 0:00:05
   -- ------------------------------------- 1.1/15.8 MB 3.9 MB/s eta 0:00:04
   --- ------------------------------------ 1.4/15.8 MB 4.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.7/15.8 MB 4.6 MB/s eta 0:00:04
   ----- ---------------------------------- 2.0/15.8 MB 4.8 MB/s eta 0:00:03
   ----- -

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'



In [2]:
import numpy as np

In [18]:
random_int_array = np.random.randint(1, 50, size=(10))
random_int_array



array([32, 40, 38, 20, 31, 35, 39, 16, 41, 48])

In [15]:
random_int_array.dtype

dtype('int32')

In [16]:

print(np.ndim(random_int_array))
random_int_array.size


1


10

In [17]:
random_int_array = np.random.randint(10, 100, size=(2, 5))
print(random_int_array)
print(random_int_array.shape)


[[93 48 81 51 40]
 [88 37 90 74 88]]
(2, 5)
