In [4]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 819.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 991.0 kB/s eta 0:00:16
   ---------------------------------------- 0.1/15.8 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/15.8 MB 1.0 MB/s eta 0:00:16
   ---------------------------------------- 0.2/15.8 MB 1.2 MB/s eta 0:00:14
    --------------------------------------- 0.2/15.8 MB 1.0 MB/s eta 0:00:16
    --------------------------------------- 0.3/15.8 MB 1.1 MB/s eta 0:00:14
    --------------------------------------- 0.3/15.8 MB 981.5 kB/s eta 0:00:16
    --------------------

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [10]:
random_int_array = np.random.randint(1, 50, size=(10))
print(random_int_array)
print(np.mean(random_int_array))

17.4


In [13]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
print(arr1)
arr2 = np.array([[1, 20, 90], [4,80, 6], [5, 6, 7]])
print(arr2)
result = np.add(arr1,arr2)
print(result)
result2=np.mean(result)
print(result2)

[[1 2 3]
 [4 5 6]
 [5 6 7]]
[[ 1 20 90]
 [ 4 80  6]
 [ 5  6  7]]
[[ 2 22 93]
 [ 8 85 12]
 [10 12 14]]
28.666666666666668


In [15]:

random_int_array = np.random.randint(1,100, size=(20))
print(random_int_array)
condition = random_int_array  > 50
filtered_arr =random_int_array[condition]
filtered_arr

[50  1  4 99  5 73 75 12 58  2 66  3 99 67 87 17  6 19 29 28]


array([99, 73, 75, 58, 66, 99, 67, 87])

In [20]:

arrNew = np.array([1, 2, 3,4, 5, 6,7,8,9,10])
np.random.shuffle(arrNew)
condition =  arrNew > 50
arrNew[condition]

arrNew


array([ 3,  1,  4,  6,  2,  9,  8,  7,  5, 10])